### ISSUE TITLE
Question: simulate a flapping service

### ISSUE THREAD

**Issue by flaccid** [ndelitski/rancher-alarms#35]
Need to look at how to simulate a degraded stack/service.

Running an alpine container with a command that doesn't exist is an easy way to have a flapping service continue to go to degraded. This service doesn't appear to be picked up by rancher-alarms - I'm thinking that this may be because rancher alarms will only add services to monitor on startup that are currently active/healthy?

Also if services are added after rancher-alarms is started up will they be detected or is this a feature we need to add to detect new stacks/services?

**Comment by ndelitski** [comment]
Hello @flaccid ! I suppose the flapping service was not recognized because program starts and ends almost instantly, rancher-alarms polls every service by small intervals and compare service status between these checks, try to add a sleep command before.
Rancher-alarms detects new services on the fly, of course if their names meet filter setting.

**Comment by flaccid** [comment]
`sleep` - a great idea, thanks !
